-- DROP CHILD TABLES FIRST (no table should reference them anymore)
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS REPORT;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS ANNOUNCEMENT;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS COMPLAINT;
DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS CITIZEN;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FEE;

-- DROP ADDRESS RELATED TABLES
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS BUILDING;
DROP TABLE IF EXISTS STREET;
DROP TABLE IF EXISTS CITY;

-- DROP UTILITY TABLES
DROP TABLE IF EXISTS TASK_STATUSES;
DROP TABLE IF EXISTS REQ_STATUSES;
DROP TABLE IF EXISTS SETTINGS_TAX;
DROP TABLE IF EXISTS LOCATION_TYPE;
DROP TABLE IF EXISTS REP_TYPE;
DROP TABLE IF EXISTS REQUEST_TYPES;
DROP TABLE IF EXISTS ROLES;