DELETE FROM NOTIFICATION;
DELETE FROM ISSUED_DOCUMENT;
DELETE FROM REPORT;
DELETE FROM TASK;
DELETE FROM DOCUMENT;
DELETE FROM REQUEST;
DELETE FROM COMPLAINT;
DELETE FROM EVENT;
DELETE FROM ANNOUNCEMENT;

DELETE FROM EMPLOYEE;
DELETE FROM CITIZEN;
DELETE FROM USERS;

DELETE FROM PAYMENT;
DELETE FROM FEE;
DELETE FROM SETTING_FEES;

DELETE FROM LOCATION;
DELETE FROM BUILDING;
DELETE FROM STREET;
DELETE FROM CITY;

DELETE FROM LOCATION_TYPE;

DELETE FROM COMPLAINT_TYPE;
DELETE FROM DOC_TYPE;
DELETE FROM TASK_STATUSES;
DELETE FROM REP_TYPE;
DELETE FROM REQUEST_TYPES;
DELETE FROM REQ_STATUSES;

DELETE FROM ROLES;
DELETE FROM SETTINGS_TAX;